---
- name: install Redis server
  apt: name=redis-server state=installed

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    mode: 0644
  notify: restart redis

- name: check if Redis is enabled on reboot
  service: name=redis-server enabled=yes

- name: check if Redis is running
  service: name=redis-server state=started
