---
- name: install rabbitmq
  apt: pkg=rabbitmq-server state=installed force=yes

- name: add rabbitmq erlang cookie
  template: >
    src=erlang.cookie.j2 dest={{ rabbitmq.erlang_cookie_location }}
    owner=rabbitmq group=rabbitmq mode=0400
  register: erlang_cookie

- name: enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing
  notify:
  - restart rabbitmq
